/// Model
/// Manipulação de dados. validações, leitura e escrita...
/// Dados: formulários, publicações etc...

/// View
/// Camada de intereção com o utilizador.
/// Elementos: Botões, formulários etc...

/// Controller.
/// Recebe as interações do utilizador.
/// Ação de: Botões, formulários etc...

/// Store